export const LOAD_RESTAURANTS = "LOAD_RESTAURANTS";

export const ADD_RESTAURANT = "ADD_RESTAURANT";

export const APPLY_FILTER = "APPLY_FILTER";

export const REMOVE_FILTER = "REMOVE_FILTER";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const SET_CURRENT_RESTAURANT_ID = "SET_CURRENT_RESTAURANT_ID";

export const SET_MODAL_OPEN_STATE = "SET_MODAL_OPEN_STATE";