export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';

export const SET_CURRENT_RESTAURANT = 'SET_CURRENT_RESTAURANT';

export const ADD_RESTAURANT = 'ADD_RESTAURANT';

export const ADD_FILTER = 'ADD_FILTER';

export const REMOVE_FILTER = 'REMOVE_FILTER';