export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';

export const SET_CURRENT_RESTAURANT = 'SET_CURRENT_RESTAURANT';

export const ADD_RESTAURANT = 'ADD_RESTAURANT';

export const APPLY_FILTER = 'APPLY_FILTER';

export const REMOVE_FILTER = 'REMOVE_FILTER';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';